apiVersion: v1
kind: ResourceQuota
metadata:
  name: taskmanager-quota
  namespace: taskmanager # même namespace que 00-namespace.yaml
spec:
  hard:
    requests.cpu: "1"       # limite totale CPU pour tous les Pods du namespace
    requests.memory: "512Mi"  # limite totale mémoire (ex: 512Mi, 1Gi...)
    limits.cpu: "2"
    limits.memory: "2Gi"
    pods: "10"             # nombre maximum de Pods autorisés dans ce namespace

---
apiVersion: v1
kind: LimitRange
metadata:
  name: taskmanager-limits
  namespace: taskmanager
spec:
  limits:
    - type: Container
      default:                # valeurs appliquées si le conteneur ne définit pas de limits
        cpu: "250m"
        memory: "256Mi"
      defaultRequest:         # valeurs appliquées si le conteneur ne définit pas de requests
        cpu: "100m"
        memory: "128Mi"
      max:                    # valeurs maximales qu'un conteneur peut demander
        cpu: "500m"
        memory: "512Mi"
