apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: taskmanager-hpa
  namespace: taskmanager
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: taskmanager
  minReplicas: 2   # valeur imposée par les consignes
  maxReplicas: 6   # valeur imposée par les consignes
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
                              # Trop bas = scale trop souvent. Trop haut = réaction lente.
                              # Justifiez votre choix dans votre rendu.
    # ??? (optionnel) Ajoutez une métrique mémoire si metrics-server le supporte
